### ISSUE TITLE
Getting `No route to host (os error 113)` even though client can ping the server and ports are open in IPTables…

### ISSUE THREAD

**Issue by vinivosh** [htrefil/rkvm#79]
Hello! First of all, thanks for this software.

I have been getting the error below when trying to connect my work laptop (client) to my desktop PC (server) in my home network.

```
sudo rkvm-client /etc/rkvm/client.toml
ERROR rkvm_client: Error: Network error: No route to host (os error 113)
```

I have assigned static IP addresses to both my client (`192.168.100.11`) and server (`192.168.100.10`) PCs. I can even ping them normally from each other, with < 2 ms average rtt, so they're definitely connected in the same network and can see each other.

I have generated the certificate and private keys using `rkvm-certificate-gen -i 192.168.100.10 -D 365 /etc/rkvm/certificate.pem /etc/rkvm/key.pem` and copied the certificate to `/etc/rkvm/certificate.pem` in the client machine.

I have also opened the `5258` port in the client **AND** server with `sudo iptables -A INPUT -p tcp --dport 5258 -j ACCEPT && sudo iptables -A INPUT -p udp --dport 5258 -j ACCEPT`.

Still, the error persists. I don't understand why and am not able to find anything online to point me to a direction. Could this be a firewall issue? Client uses `ufw`, and I haven't messed with its configs yet. Server does not use `ufw`. Could that be it?

Using the server and client systemd services instead of the terminal commands doesn't solve the issue, either.

I have tried using [**zerotier-one**](https://www.zerotier.com/) to create a virtual LAN between the two computers too, to no avail. Even while being able to ping their managed IPs from each other, the problem persisted!

I even tried other ports, like `25565`, to no avail.

My current `/etc/rkvm/server.toml`:
```toml
listen = "0.0.0.0:25565"
# See `switch-keys.md` in the repository root for the list of all possible keys.
switch-keys = ["left-brace", "right-brace", "apostrophe"]
# Whether switch key presses should be propagated on the server and its clients.
# Optional, defaults to true.
# propagate-switch-keys = true
certificate = "/etc/rkvm/certificate.pem"
key = "/etc/rkvm/key.pem"

# This is to prevent malicious clients from connecting to the server.
# Make sure this matches your client's config.
#
# Change this to your own value before deploying rkvm.
password = "minecraft123"

```

My current `/etc/rkvm/client.toml`:
```toml
# Static IP for my home computer, the server
server = "192.168.100.10:25565"
certificate = "/etc/rkvm/certificate.pem"

# This is to prevent malicious clients from connecting to the server.
# Make sure this matches your server's config.
#
# Change this to your own value before deploying rkvm.
password = "minecraft123"

```

More info: my server PC is X11 + BSPWM, while my client PC is Wayland + Hyprland. Although, if I understood the implementation used in rkvm, this shouldn't be relevant at all.
